openapi: '3.0.2'
info:
  title: Part 1
  version: '1.0.0'
servers:
  - url: https://api.server.test/v1
paths:
  /convenors:
    get:
      responses:
        '200':
          description: OK
    post:
      responses:
        '201':
          description: OK
    
    put:
      responses:
        '200':
          description: OK

    #delete a specific convenor
    delete:
      responses:
        '200':
          description: OK
